//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnTangle.Windows {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShowTransliteration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShowTransliteration() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnTangle.Windows.ShowTransliteration", typeof(ShowTransliteration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Top, Bottom, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles ButtonClose_Anchor {
            get {
                object obj = ResourceManager.GetObject("ButtonClose.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.FlatStyle, аналогичного Flat.
        /// </summary>
        internal static System.Windows.Forms.FlatStyle ButtonClose_FlatStyle {
            get {
                object obj = ResourceManager.GetObject("ButtonClose.FlatStyle", resourceCulture);
                return ((System.Windows.Forms.FlatStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.ImeMode, аналогичного NoControl.
        /// </summary>
        internal static System.Windows.Forms.ImeMode ButtonClose_ImeMode {
            get {
                object obj = ResourceManager.GetObject("ButtonClose.ImeMode", resourceCulture);
                return ((System.Windows.Forms.ImeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=370,Y=0}.
        /// </summary>
        internal static System.Drawing.Point ButtonClose_Location {
            get {
                object obj = ResourceManager.GetObject("ButtonClose.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.Padding, аналогичного {Left=1,Top=3,Right=1,Bottom=3}.
        /// </summary>
        internal static System.Windows.Forms.Padding ButtonClose_Margin {
            get {
                object obj = ResourceManager.GetObject("ButtonClose.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=30, Height=30}.
        /// </summary>
        internal static System.Drawing.Size ButtonClose_Size {
            get {
                object obj = ResourceManager.GetObject("ButtonClose.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 1.
        /// </summary>
        internal static int ButtonClose_TabIndex {
            get {
                object obj = ResourceManager.GetObject("ButtonClose.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X.
        /// </summary>
        internal static string ButtonClose_Text {
            get {
                return ResourceManager.GetString("ButtonClose.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Boolean, аналогичного True.
        /// </summary>
        internal static bool PanelTitleBar_AutoScroll {
            get {
                object obj = ResourceManager.GetObject("PanelTitleBar.AutoScroll", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.DockStyle, аналогичного Top.
        /// </summary>
        internal static System.Windows.Forms.DockStyle PanelTitleBar_Dock {
            get {
                object obj = ResourceManager.GetObject("PanelTitleBar.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=0,Y=0}.
        /// </summary>
        internal static System.Drawing.Point PanelTitleBar_Location {
            get {
                object obj = ResourceManager.GetObject("PanelTitleBar.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.Padding, аналогичного {Left=4,Top=4,Right=4,Bottom=4}.
        /// </summary>
        internal static System.Windows.Forms.Padding PanelTitleBar_Margin {
            get {
                object obj = ResourceManager.GetObject("PanelTitleBar.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=400, Height=30}.
        /// </summary>
        internal static System.Drawing.Size PanelTitleBar_Size {
            get {
                object obj = ResourceManager.GetObject("PanelTitleBar.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 0.
        /// </summary>
        internal static int PanelTitleBar_TabIndex {
            get {
                object obj = ResourceManager.GetObject("PanelTitleBar.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.AnchorStyles, аналогичного Top, Bottom, Left, Right.
        /// </summary>
        internal static System.Windows.Forms.AnchorStyles TextBoxOutput_Anchor {
            get {
                object obj = ResourceManager.GetObject("TextBoxOutput.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Font, аналогичного [Font: Name=Comic Sans MS, Size=9,75, Units=3, GdiCharSet=1, GdiVerticalFont=False].
        /// </summary>
        internal static System.Drawing.Font TextBoxOutput_Font {
            get {
                object obj = ResourceManager.GetObject("TextBoxOutput.Font", resourceCulture);
                return ((System.Drawing.Font)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Point, аналогичного {X=0,Y=30}.
        /// </summary>
        internal static System.Drawing.Point TextBoxOutput_Location {
            get {
                object obj = ResourceManager.GetObject("TextBoxOutput.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.Padding, аналогичного {Left=8,Top=4,Right=8,Bottom=4}.
        /// </summary>
        internal static System.Windows.Forms.Padding TextBoxOutput_Margin {
            get {
                object obj = ResourceManager.GetObject("TextBoxOutput.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=400, Height=78}.
        /// </summary>
        internal static System.Drawing.Size TextBoxOutput_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("TextBoxOutput.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=400, Height=78}.
        /// </summary>
        internal static System.Drawing.Size TextBoxOutput_MinimumSize {
            get {
                object obj = ResourceManager.GetObject("TextBoxOutput.MinimumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Windows.Forms.RichTextBoxScrollBars, аналогичного Vertical.
        /// </summary>
        internal static System.Windows.Forms.RichTextBoxScrollBars TextBoxOutput_ScrollBars {
            get {
                object obj = ResourceManager.GetObject("TextBoxOutput.ScrollBars", resourceCulture);
                return ((System.Windows.Forms.RichTextBoxScrollBars)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Size, аналогичного {Width=400, Height=78}.
        /// </summary>
        internal static System.Drawing.Size TextBoxOutput_Size {
            get {
                object obj = ResourceManager.GetObject("TextBoxOutput.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Int32, аналогичного 1.
        /// </summary>
        internal static int TextBoxOutput_TabIndex {
            get {
                object obj = ResourceManager.GetObject("TextBoxOutput.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string TextBoxOutput_Text {
            get {
                return ResourceManager.GetString("TextBoxOutput.Text", resourceCulture);
            }
        }
    }
}
